### ISSUE TITLE
image/name links

### ISSUE THREAD

**Issue by vlost** [Mr-HaleYa/mywatersitemisc#10]
when you click on your image/name none of the links work
![image](https://user-images.githubusercontent.com/10885939/84611299-a4a8f200-ae7a-11ea-84ee-3b928f38090d.png)

**Comment by Mr-HaleYa** [comment]
@vlost can you explain with more than 12 words? what page? user or admin? screenshot?

**Comment by 0xCTF** [comment]
yes i didn't worked on that dropdown list yet, i just was about to delete it and put only logout
do we need those options?
i was thinking about settings, where the account owner can change his details(not username) and password without needing to search for it in manage admin and user will be able to change his details too
for activity log, do we need it ?
idk about profile, it will show details about the account owner

**Comment by Mr-HaleYa** [comment]
@0xCTF I think we should only have settings and log out and in the settings, they can change their email, password, phone number, Billing info, and address.

**Comment by 0xCTF** [comment]
**Fixed**
![image](https://user-images.githubusercontent.com/42708935/84808051-06469900-b000-11ea-90a0-937ce137e746.png)
Note: still settings page to work on it

**Comment by 0xCTF** [comment]
**settings works now**

**Comment by Mr-HaleYa** [comment]
Great work it is working
