### ISSUE TITLE
User not fully deleted

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#11]
Users_sites not deleted when a user is removed

https://drive.google.com/file/d/1j6jCdmtglO6cIjIufCC5eAqRg4FRHzMO/view

**Comment by 0xCTF** [comment]
**Nice catch 
Fixed for admins and users**
Note: online files are not updated yet

**Comment by Mr-HaleYa** [comment]
@0xCTF thank you,  message me once the files are uploaded

**Comment by Mr-HaleYa** [comment]
great job all is working now
