### ISSUE TITLE
All WP is broke...

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#12]
Since you change the files nothing that is related to Wordpress is working correctly and I really like using Wordpress to edit pages, I think we need to redo the way that your pages were added because I would at least like the homepage to have WordPress functionality. I at least need to be able to sign in to WordPress to be able to update plugins and themes

https://drive.google.com/file/d/1v6wOuNc6QJ7ibZh6dJvTjvN4diAK69hL/view

**Comment by 0xCTF** [comment]
ok but that's only for the homepage, all other pages, (list, map, graph,dashboard) does not use wordpress
