### ISSUE TITLE
Add solar_voltage 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#13]
I would like to add solar_voltage to the list of admin graphs and readings. it is the same as battey_voltage but tells us if the solar panels are working and at what times. I can make the new places in the database but I don't want to break your pages. Please message @0xCTF  me and we can work on this.  Adding  this is a lot of work on both our part lol

**Comment by 0xCTF** [comment]
**Done**

**Comment by Mr-HaleYa** [comment]
beautiful 👍
