### ISSUE TITLE
some visual errors

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#15]
When deleting a user it says, Admin

![28](https://user-images.githubusercontent.com/42821995/84841733-63dae580-b000-11ea-9db0-11b3a4367091.png)

---

some random text in the top right when editing a users info

![27](https://user-images.githubusercontent.com/42821995/84841763-80771d80-b000-11ea-8b88-c738106aa9be.png)

**Comment by 0xCTF** [comment]
what i remplace it (Close?) with ?

**Comment by Mr-HaleYa** [comment]
no lol, either get rid of it

**Comment by 0xCTF** [comment]
Done

**Comment by Mr-HaleYa** [comment]
looks good
