### ISSUE TITLE
Add last reading timestamp 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#18]
should show the timestamp of the last reading that that was taken, have it as hh-mm dd-MM

![31](https://user-images.githubusercontent.com/42821995/84955098-deb10880-b0b3-11ea-99e2-239e3adf3336.png)

**Comment by 0xCTF** [comment]
timestamp is now formated as hh-mm dd-MM but if i'm new user, maybe i'll misunderstood the dd-MM
new
![image](https://user-images.githubusercontent.com/42708935/85056759-b3074e80-b197-11ea-8538-cb89a1dc8808.png)
old
![image](https://user-images.githubusercontent.com/42708935/85056822-c9150f00-b197-11ea-926e-2df8aa322e64.png)


**Fixed**

**Comment by Mr-HaleYa** [comment]
Can you make that into 12 hours since people in America don't you used 24 hours, also, the timing is wrong because we save the data in UTC so there needs to be some kind of function that converts it into our time zone. That goes to all things that use dates, like the graphs

**Comment by 0xCTF** [comment]
**Can you make that into 12 hours since people in America don't you used 24 hours,**
Done
**the timing is wrong because we save the data in UTC so there needs to be some kind of function that converts it into our time zone. That goes to all things that use dates, like the graphs**
MST ?

**Comment by 0xCTF** [comment]
**Fixed**
now it check ip adress location timezone and convert UTC to that timezone

**Comment by 0xCTF** [comment]
Note: the code somehow is not stable, sometimes it gives the wrong timezone 
check from here
https://www.mywater.site/time.php

**Comment by 0xCTF** [comment]
the other solution is making a new field in Manage > USER to add the new client timezone and save it in database
that's better than ip adress, from which it said here https://stackoverflow.com/questions/743505/how-to-get-time-zone-through-ip-address-in-php

but if the client is in travel in different country/state, things will not work correclty only if he/she changed timezone from Settings(the top right option)

**Comment by 0xCTF** [comment]
nevermind, the code is not correct; still working on it.

**Comment by Mr-HaleYa** [comment]
> Note: the code somehow is not stable, sometimes it gives the wrong timezone
> check from here
> https://www.mywater.site/time.php

it is working for ma and always gives me the same TZ. If you use a VPN it will switch to all over the world

**Comment by Mr-HaleYa** [comment]
@0xCTF I think we should just add it as a field for users during signup and add it to the user table as a new column. they should not be traveling to other timezones and if they do they can do the math.

**Comment by 0xCTF** [comment]
**All Done**

**Comment by Mr-HaleYa** [comment]
Its looking good. The only thing that is missing is daylight savings time but that shouldn't be to hard to do. opened on #31
