### ISSUE TITLE
cant go back to "water highlighted" style on map once clicked to a different style  

### ISSUE THREAD

**Issue by vlost** [Mr-HaleYa/mywatersitemisc#19]

**Comment by Mr-HaleYa** [comment]
@vlost you need to have descriptions and/or a screenshot or vid

**Comment by Mr-HaleYa** [comment]
https://drive.google.com/file/d/1338xpq5ALRVyvhpO0id5bs54PmE8s72z/view

**Comment by 0xCTF** [comment]
i was trying for couple hours, still can't do it and i don't think it's possible.
Here's two answers from stackoverflow
https://stackoverflow.com/questions/3918608/google-maps-api-styled-map-with-satellite-water
![image](https://user-images.githubusercontent.com/42708935/85064788-febff500-b1a3-11ea-9ed6-4eee8e05985b.png)

https://stackoverflow.com/questions/46279135/google-styled-maps-can-be-applied-to-satellite-map-type
![image](https://user-images.githubusercontent.com/42708935/85064841-1303f200-b1a4-11ea-943b-991d52c713d3.png)

**Comment by Mr-HaleYa** [comment]
So if you switch a map and then switch back it just deletes your styling?

**Comment by 0xCTF** [comment]
> So if you switch a map and then switch back it just deletes your styling?

Yeah because it back to the real map instead of the custom one, i'll ask stackoverflow about that
