### ISSUE TITLE
Dont show flow on popup if weir==0

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#2]
When the weir type is set to ==0 then don't show flow on the popup bc flow is not supported, just show the depth.

https://drive.google.com/file/d/1GHQM7jOIkL-tz8-4GA3WLm2kYvHVi7Fg/view?usp=sharing

**Comment by 0xCTF** [comment]
DONE

**Comment by Mr-HaleYa** [comment]
@0xCTF  Great work on this!
