### ISSUE TITLE
User changing station name crashes website

### ISSUE THREAD

**Issue by vlost** [Mr-HaleYa/mywatersitemisc#20]
![image](https://user-images.githubusercontent.com/10885939/84979195-163ba700-b0ec-11ea-93db-6af0f78bde80.png)

**Comment by Mr-HaleYa** [comment]
Notice: Undefined index: flowonOroff in /home/u287141768/domains/mywater.site/public_html/process_user.php on line 30

Notice: Undefined index: onOroff in /home/u287141768/domains/mywater.site/public_html/process_user.php on line 31

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'show_flow' in 'field list' in /home/u287141768/domains/mywater.site/public_html/process_user.php:43 Stack trace: #0 /home/u287141768/domains/mywater.site/public_html/process_user.php(43): PDOStatement->execute(Array) #1 {main} thrown in /home/u287141768/domains/mywater.site/public_html/process_user.php on line 43

**Comment by 0xCTF** [comment]
**Fixed**
