### ISSUE TITLE
Transfer all data to new station

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#22]
If a station is struck by lightning or something and it is completely dead we need to be able to transfer all data over to a new station along with all users and settings.  Basically in the code, it would just replace the old table name in PHPMyAdmin with the name of the new station and replace the old name that is assigned to users with the new one

**Comment by 0xCTF** [comment]
**Done**

**Comment by Mr-HaleYa** [comment]
I love it
