### ISSUE TITLE
Change list layout

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#23]
For users and admin, it only needs to show the name (center aligned) Water depth, and Flow Rate

![32](https://user-images.githubusercontent.com/42821995/85036598-90e2e180-b141-11ea-9b74-27689a50490d.png)

**Comment by 0xCTF** [comment]
![image](https://user-images.githubusercontent.com/42708935/85053922-28245500-b193-11ea-94f2-d6fd5dbfebd0.png)
normal vs center aligned 
so, dO It ?

**Comment by 0xCTF** [comment]
**Fixed**

**Comment by Mr-HaleYa** [comment]
Can you make the station named larger? Maybe a little bold,

**Comment by 0xCTF** [comment]
**Done**

**Comment by Mr-HaleYa** [comment]
beautiful
