### ISSUE TITLE
new issue about autofill 

### ISSUE THREAD

**Issue by 0xCTF** [Mr-HaleYa/mywatersitemisc#26]
Yes, I kept having that problem when creating new users it would give them my username and password because it would autofill it into the tabs and I would have to delete it out and then type it in manually and it was really annoying. To remove autofill from the entire website except for the homepage so that you can autofill your username and password into the login

_Originally posted by @Mr-HaleYa in https://github.com/Mr-HaleYa/mywatersitebuglog/issues/17#issuecomment-645603379_

**Comment by Mr-HaleYa** [comment]
Looks really good 👍 If you could add this to user settings I would be really happy

**Comment by 0xCTF** [comment]
fixed

**Comment by Mr-HaleYa** [comment]
THANK YOU!!!
