### ISSUE TITLE
No daylight savings time on timestamps

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#31]
Timestamps work they just are off by one hour

![35](https://user-images.githubusercontent.com/42821995/85217899-64ea7a80-b352-11ea-9085-33002e6780c5.png)

**Comment by 0xCTF** [comment]
https://drive.google.com/file/d/1n4hCN9_cBUrLhcfvgSL6AiizMXWF5jfb/view?usp=sharing

if GMT-6 is the timezone there, so when i change it gives the correct time, soooo
i think i'm misunderstanding something here, i'm confused

**Comment by Mr-HaleYa** [comment]
this issue has progressed a lot today, good work @0xCTF

**Comment by Mr-HaleYa** [comment]
great work
