### ISSUE TITLE
Idea for viewing data 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#32]
@vlost @0xCTF 
So maybe we should add a calendar to the graphs page so a user could select a specific day that they want to view data for?  or we could do a duel slider that shows all data between its points so they could move the left to may 1st and the right to May 7th and see 1 week of data between those times.

We currently use chartJS but look at this example and play with the graph https://jsfiddle.net/chartiq/dtug29yx/

**Comment by vlost** [comment]
ether way is fine

**Comment by 0xCTF** [comment]
**Done**

**Comment by Mr-HaleYa** [comment]
Thank you
