### ISSUE TITLE
Add unit labels 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#35]
Add the unit labels to these please, so we know what they are lol. You can add the easy ones first then do the user_units after finishing #34 

![37](https://user-images.githubusercontent.com/42821995/85253951-6f714680-b41c-11ea-9218-aa39b1cb7014.png)
![38](https://user-images.githubusercontent.com/42821995/85254836-61bcc080-b41e-11ea-826f-026813724eb0.png)
![39](https://user-images.githubusercontent.com/42821995/85256217-ffb18a80-b420-11ea-9e1a-a079dbb56ab7.png)

**Comment by 0xCTF** [comment]
Still the graphs

**Comment by Mr-HaleYa** [comment]
nice work I opened #39 for graphs
