### ISSUE TITLE
change Graph layout 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#38]
https://drive.google.com/file/d/17UgnOYEeEG8N5hNnWKFNu8VX5A4LHfhz/view

Change the graphs so that each graph auto loads a user's default unit type, and change how the different units are chosen.

**Comment by 0xCTF** [comment]
**Done**

**Comment by Mr-HaleYa** [comment]
LOVE IT ❤️
