### ISSUE TITLE
Unit conversion for User_Units

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#39]
Units need to be converted to the correct type. Units need to be added to the graph.

This may be best to do after #38

**Comment by 0xCTF** [comment]
**1/2 done**

**Comment by Mr-HaleYa** [comment]
👍

**Comment by 0xCTF** [comment]
**Fixed**

**Comment by Mr-HaleYa** [comment]
nice I love the units on the graph
