### ISSUE TITLE
way to many decimals 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#40]
When converting to a different unit type there is no cut-off so some of them have like 30 decimal places. Have it cut off at the hundredths place (0.00). This will have to be added to all unit conversions 

https://drive.google.com/file/d/1vSc_FxG7q76tW5cKdd1pECdn2AcsHaOW/view

**Comment by Mr-HaleYa** [comment]
this is what I use to get 2 decimals
``` $flow=number_format($flowRate, 2, '.', ""); //2 decimal points ```
it corrects rounding errors so it does the math right 

its PHP so it might not work for javascript...

**Comment by 0xCTF** [comment]
ok but many values in some units will be 0.00 because the full value is like 0.0000654597
is that ok ?

**Comment by Mr-HaleYa** [comment]
temp is the only one that needs to be forced .00 the others are fine .0000000000000

**Comment by 0xCTF** [comment]
**Fixed**

**Comment by Mr-HaleYa** [comment]
I like it
