### ISSUE TITLE
visual fixes

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#46]
swap places
![53](https://user-images.githubusercontent.com/42821995/85913112-1ecc6580-b7ef-11ea-96b2-0cff1acfb9d8.png)
change layout to this
![54](https://user-images.githubusercontent.com/42821995/85913147-67841e80-b7ef-11ea-8598-bcfd94e7e2f5.png)
swap places
![55](https://user-images.githubusercontent.com/42821995/85913168-94383600-b7ef-11ea-9966-c6c7c3b5d31f.png)
swap places
![56](https://user-images.githubusercontent.com/42821995/85913169-94d0cc80-b7ef-11ea-96fe-965b32fe98d2.png)
swap places
![57](https://user-images.githubusercontent.com/42821995/85913182-b9c53f80-b7ef-11ea-8f81-18f6a87ee9bd.png)
add mm labels to these, you can put it in the box or next to the name like "distance to ground in mm)
![583](https://user-images.githubusercontent.com/42821995/85913267-669fbc80-b7f0-11ea-8f8d-269cabfe12cc.png)

**Comment by 0xCTF** [comment]
**Fixed**

**Comment by Mr-HaleYa** [comment]
looks good except for the mm, ill open a new issue for that bc It might be a little work
