### ISSUE TITLE
Station settings visual improvements 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#48]
Basically remove the mm label that you added inside the box and put a hover pop-up outside the next to the name in the information column. 

https://drive.google.com/file/d/1NhyyehFrqprL3Wr_2-e0J9BtXY8cAd3r/view

for weir type add (0-no weir 1-rectangular Weir 2-trapezoidal Weir 3-90 degrees v-notch weir)

**Comment by Mr-HaleYa** [comment]
might help https://www.w3schools.com/css/css_tooltip.asp

**Comment by 0xCTF** [comment]
**Fixed**

**Comment by Mr-HaleYa** [comment]
@0xCTF 
lol, you forgot the weir type... 

> for weir type add (0-no weir 1-rectangular Weir 2-trapezoidal Weir 3-90 degrees v-notch weir)

**Comment by 0xCTF** [comment]
> @0xCTF
> lol, you forgot the weir type...
> 
> > for weir type add (0-no weir 1-rectangular Weir 2-trapezoidal Weir 3-90 degrees v-notch weir)

This phrase shown when mouse hover the ❔ ?

**Comment by Mr-HaleYa** [comment]
yes, just like you have it here
![image](https://user-images.githubusercontent.com/42821995/86213271-a9d29600-bb36-11ea-8f6a-fc76442a5d90.png)

**Comment by Mr-HaleYa** [comment]
love it ❤️
