### ISSUE TITLE
auto detect user units for graph

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#50]
need a new way to auto-detect and apply a users default unit type bc I keep getting this and I had others test and they would get it too sometimes 
![62](https://user-images.githubusercontent.com/42821995/85939800-89f06780-b8d5-11ea-8cec-00f91230150d.png)

**Comment by 0xCTF** [comment]
**Fixed**

**Comment by Mr-HaleYa** [comment]
lol 1-sec delay seems to have fixed it 🤣 RIP fast internet
