### ISSUE TITLE
Data updates 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#51]
For now, it would be easier to add a button that says "Refresh"
![64](https://user-images.githubusercontent.com/42821995/86070528-38152200-ba3a-11ea-9ecb-f08df8e95d60.png)

**Comment by 0xCTF** [comment]
Last readings is live updated, but the time&date still not live updated

**Comment by Mr-HaleYa** [comment]
live updates are not working for me and the time and date also need to be fixed before closing. It does not update if I have a station page open until I refresh the page. I also discovered a bug when a station has weir == 0 the lastreading box does weird stuff after 5 sec. 

on load 
![73](https://user-images.githubusercontent.com/42821995/86450931-767b3d00-bcd7-11ea-82fc-55d225461559.png)
after 5 sec
![72](https://user-images.githubusercontent.com/42821995/86450906-71b68900-bcd7-11ea-9536-d57b3ca02488.png)

**Comment by 0xCTF** [comment]
**Fixed** the weird thing when weir_type==0, but still need some work on date&time
i tested the live updates by changing the last readings values manually in db and it changed after 5sec in the last readings

**Comment by Mr-HaleYa** [comment]
It works if you change old data manually but it does not show new data being added to the database...

**Comment by Mr-HaleYa** [comment]
Some requirements, if you want to do auto data updates
new data is "pulled for" every ~45 sec.
new data is shown on the graph when found
new data is shown on the last reading when found.

we only need this on the STATION page. no other pages need live data

**Comment by Mr-HaleYa** [comment]
A refresh button has been added and works great, once live updates are added we will open a new issue.
