### ISSUE TITLE
Change when some items are shown

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#55]
Right now "flow" and "volume" only show if weir type is != 0. 
It needs to be changed so that if 

if Flow == -1 don't show  
if volume == -1 don't show 

This will make it so I can add wire types that just use Flow or just use volume or are not wierType 0 but don't use flow or volume like #54 

It needs to be changed on the whole site (map pins, list page, last reading, graphs)

**Comment by 0xCTF** [comment]
**Still some work on the map pop-up pins, flow: -1 ,for some reasons, still showing up**

**Comment by Mr-HaleYa** [comment]
Map pin popup and graphs

**Comment by 0xCTF** [comment]
**Fixed**

**Comment by Mr-HaleYa** [comment]
Nice
