### ISSUE TITLE
Add IMEI field to StationMeta

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#57]
I need to add this so I know what sim card is being used by the station so I quit losing them... We can add this when we are doing #56 message me when ready

**Comment by Mr-HaleYa** [comment]
@0xCTF 
I have made all the changes in my code that are needed to add this. I just need you to be ready then I will upload it and alter meta tables

**Comment by Mr-HaleYa** [comment]
added imei column to Station_meta table

**Comment by Mr-HaleYa** [comment]
I added all the code for IMEI to the server and it is working and hasn't crashed the site lol. All you have to do is add a place where we can see what the IMEI is. You should replace the install date box with "IMEI"

**Comment by 0xCTF** [comment]
**FIXED**

**Comment by Mr-HaleYa** [comment]
oh it's beautiful
