### ISSUE TITLE
User BROKEN 

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#60]
when signed in as a user a LOT of things don't work. hopefully just small fixes but idk

https://drive.google.com/file/d/1cu3gZGNG-6RJuWiwo3xFLwSo2tCb6vAE/view

**Comment by 0xCTF** [comment]
**fixed** by fixing https://github.com/Mr-HaleYa/mywatersitemisc/issues/61
