### ISSUE TITLE
change "Show By" option in list page

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#65]
Make it two buttons that are next to each other like the gaphs instead of a dropdown menu. 
![image](https://user-images.githubusercontent.com/42821995/88991265-7f8f0800-d29d-11ea-8192-32faeeb2e810.png)

**Comment by 0xCTF** [comment]
**Fixed**

**Comment by Mr-HaleYa** [comment]
perfect
