### ISSUE TITLE
click on "more details" in list of stations 

### ISSUE THREAD

**Issue by vlost** [Mr-HaleYa/mywatersitemisc#7]
on station list page get rid of the "More Details" and just click anywhere in the box.
...but I really want a sort able table, if it's not too hard,  Your boxes are cool but when a customer has 100 stations it will be easier to sort thought them with a table

**Comment by Mr-HaleYa** [comment]
We need to discuss how to do this properly before attempting.

**Comment by 0xCTF** [comment]
**"on station list page get rid of the "More Details" and just click anywhere in the box."**
ok understood

**"...but I really want a sort able table, if it's not too hard, Your boxes are cool but when a customer has 100 stations it will be easier to sort thought them with a table"**
i just mentionned that in https://github.com/Mr-HaleYa/mywatersitebuglog/issues/9#issuecomment-644257484
that's what you mean right ?
the table structure will mess up the look of the stations cards(the rectangle that have the station)
so my idea is a search bar and a pages number like the manage admin/user

**"We need to discuss how to do this properly before attempting."**
agree

**Comment by 0xCTF** [comment]
**"on station list page get rid of the "More Details" and just click anywhere in the box."**
Done

**Comment by Mr-HaleYa** [comment]
only working for admins

**Comment by Mr-HaleYa** [comment]
fixed for all, great job
