### ISSUE TITLE
graph data disappears after a minuets

### ISSUE THREAD

**Issue by vlost** [Mr-HaleYa/mywatersitemisc#72]
graph becomes blank after a minuets of viewing, probably caused by live update.

![image](https://user-images.githubusercontent.com/10885939/91164687-ba157600-e68c-11ea-9199-ca427d9f7c5a.png)

**Comment by Mr-HaleYa** [comment]
I think that we could just remove live updates all together... I absolutely love it but it causes a lot of problems. and if you have a slow PC it uses a lot of CPU and if youse mobile it uses a lot of data from fetching changes 

I think that we should just put the refresh button back and try this later
