### ISSUE TITLE
SMS -> Text

### ISSUE THREAD

**Issue by vlost** [Mr-HaleYa/mywatersitemisc#76]
change "SMS" to "Text"
in the US an SMS is called a Text
![image](https://user-images.githubusercontent.com/10885939/91659083-aef68780-ea8a-11ea-957b-13fbe00e87dc.png)

**Comment by Mr-HaleYa** [comment]
Maybe they should get over it

![IMG_20200830_082457.jpg](https://user-images.githubusercontent.com/42821995/91661627-75c61380-ea9a-11ea-8b41-71225badcb3c.jpg)

![IMG_20200830_082517.jpg](https://user-images.githubusercontent.com/42821995/91661630-7a8ac780-ea9a-11ea-8527-f497c591dcb5.jpg)
