### ISSUE TITLE
Remove "User" label when logged in as user

### ISSUE THREAD

**Issue by vlost** [Mr-HaleYa/mywatersitemisc#8]
when a user is longed in don't show the user label, 
just have the admin label for admins

**Comment by Mr-HaleYa** [comment]
![26](https://user-images.githubusercontent.com/42821995/84607861-dc10a200-ae6c-11ea-8188-a9b299c9cb07.png)

**Comment by 0xCTF** [comment]
**ok consider it as done**

**Comment by 0xCTF** [comment]
**DONE**

**Comment by Mr-HaleYa** [comment]
thank you
