### ISSUE TITLE
Remove search bar

### ISSUE THREAD

**Issue by vlost** [Mr-HaleYa/mywatersitemisc#9]
search would be cool, if you can get it to work, if not get rid of it

**Comment by Mr-HaleYa** [comment]
I really don't think we need a site-wide search bar so just remove it. Maybe we could use one on the list for finding stations quickly? otherwise, we don't need it

**Comment by 0xCTF** [comment]
i just put it there because i will use it for "List" to search for a station, 
i will save the code and remove it in the next file upload

**Comment by Mr-HaleYa** [comment]
@0xCTF ok, so the search bar will only be on the list page, correct?

**Comment by 0xCTF** [comment]
@Mr-HaleYa Yes correct

**Comment by 0xCTF** [comment]
Search bar removed from all pages but only list page still have it

**Comment by Mr-HaleYa** [comment]
Great I opened a new issue for this #14
